### ISSUE TITLE
mkdir: cannot create directory ‘isofiles’: File exists

### ISSUE THREAD

**Issue by sairuk** [danmons/retronas-dist#3]
ran into this today, probably need to check for the dir first

```
Extracting iso: iso-cache/debian-11.2.0-amd64-netinst.iso...
mkdir: cannot create directory ‘isofiles’: File exists
make: *** [Makefile:23: build-debian-amd64] Error 1
```

**Comment by munderwoods** [comment]
Yeah I know about this. Did you cancel the build part way through or something? These are supposed to be removed at the end of a build. I'll remove the dir if it exists at the beginning of the build.

**Comment by sairuk** [comment]
the download failed part way through which killed the script

**Comment by munderwoods** [comment]
Yeah, this will come up a lot so I'll deal with it.
